name: Build NAPI Addons

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build_napi:
    name: Build
    strategy:
      matrix:
        kind: ['linux', 'macos', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            script: build_native.sh
          - kind: macos
            os: macOS-latest
            script: build_native.sh
          - kind: windows
            os: windows-latest
            script: build_native.ps1
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Compile
      working-directory: ${{ github.workspace }}/scripts
      run: ./${{ matrix.script }}