name: Package VSCode Plugin

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  prepare:
    name: Build Native Dependencies
    strategy:
      matrix:
        kind: ['linux', 'macos', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            script: build_native.sh
            folder_name: Linux 
          - kind: macos
            os: macOS-latest
            script: build_native.sh
            folder_name: Darwin
          - kind: windows
            os: windows-latest
            script: build_native.ps1
            folder_name: Windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Compile
      working-directory: ${{ github.workspace }}/scripts
      run: ./${{ matrix.script }}

    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.folder_name }}
        path: ${{ github.workspace }}/out/${{ matrix.folder_name }}
        retention-days: 1

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - uses: actions/checkout@v2

    - name: Retrieve Linux Artifact
      uses: actions/download-artifact@v2
      with:
        name: Linux
        path: ${{ github.workspace }}/out/Linux

    - name: Retrieve macOS Artifact
      uses: actions/download-artifact@v2
      with:
        name: Darwin
        path: ${{ github.workspace }}/out/Darwin

    - name: Retrieve Windows Artifact
      uses: actions/download-artifact@v2
      with:
        name: Windows
        path: ${{ github.workspace }}/out/Windows

    - name: Package
      run: |
        mkdir -p ${{ github.workspace }}/dist
        full_filename=$(ls ${{ github.workspace }}/out/Darwin | grep -P "libcblite\.\d\.\d\.\d\.dylib")
        short_filename=$(ls ${{ github.workspace }}/out/Darwin | grep -P "libcblite\.\d\.dylib")
        cp ${{ github.workspace }}/out/Darwin/$full_filename ${{ github.workspace }}/dist
        ln -s $full_filename ${{ github.workspace }}/dist/$short_filename
        ln -s $short_filename ${{ github.workspace }}/dist/libcblite.dylib
        cp ${{ github.workspace }}/out/Windows/cblite.dll ${{ github.workspace }}/dist
        npm install
        npm run package-only

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "vscode-cblite*"